package me.craig.college.wsc.forms;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import me.craig.college.wsc.data.DataHandler;
import me.craig.college.wsc.objects.DataTable;
import me.craig.college.wsc.objects.Projects;
import me.craig.college.wsc.utils.Utils;

import javax.swing.*;
import java.awt.*;

/* Created by Craig on 06/04/2021 */
public class EditProject {
    private JTabbedPane tabbedPane1;
    private JPanel main;
    private JSlider newScore;
    private JButton updateButton;
    private JLabel projectTitle;
    private JButton deleteProjectButton;
    private Projects.Project project;
    private static JFrame jFrame = new JFrame("Edit Project");

    public EditProject() {

        for (DataTable< Projects.Project > projectDataTable : Projects.getProjects()) {
            if (tabbedPane1.getTitleAt(0).matches("Something")) {
                tabbedPane1.setTitleAt(0, projectDataTable.getAsSelf().getProjectName());
                updateWidgetsBasedOnProject(tabbedPane1.getTitleAt(tabbedPane1.getSelectedIndex()));
                continue;
            }
            Projects.Project project = projectDataTable.getAsSelf();
            tabbedPane1.addTab(project.getProjectName(), null);
        }

        updateWidgetsBasedOnProject(tabbedPane1.getTitleAt(tabbedPane1.getSelectedIndex()));


        tabbedPane1.addChangeListener(changeEvent -> updateWidgetsBasedOnProject(tabbedPane1.getTitleAt(tabbedPane1.getSelectedIndex())));

        updateButton.addActionListener(actionEvent -> {
            Projects.getProjects().remove(project);
            project.setScore(newScore.getValue());
            DataHandler.projectToJson(project);
            Projects.addProject(project);
            WorldSkillsCompetition.updateMainTable("Projects");
            jFrame.dispose();
        });

        deleteProjectButton.addActionListener(actionEvent -> {
            Projects.getProjects().remove(project);
            DataHandler.deleteProjectFile(project);
            WorldSkillsCompetition.updateMainTable("Projects");
            jFrame.dispose();
        });
    }

    private void updateWidgetsBasedOnProject(String title) {
        for (DataTable< Projects.Project > projectDataTable : Projects.getProjects()) {
            Projects.Project project = projectDataTable.getAsSelf();
            if (project.getProjectName().matches(title)) {
                projectTitle.setText(title);
                newScore.setValue((int) project.getScore());
                this.project = project;
            }
        }
    }

    public static void showEditor() {
        if (Projects.getProjects().isEmpty()) {
            Utils.showError("No Projects to Edit!");
            jFrame.dispose();
            return;
        }
        Utils.setTheme();
        jFrame.setContentPane(new EditProject().main);
        jFrame.setSize(1000, 500);
        jFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        jFrame.setResizable(false);
        jFrame.setVisible(true);
        jFrame.setLocationRelativeTo(null);
        jFrame.setIconImage(WorldSkillsCompetition.instance.getIconLocation());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        main = new JPanel();
        main.setLayout(new GridLayoutManager(3, 3, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1 = new JTabbedPane();
        main.add(tabbedPane1, new GridConstraints(1, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Something", panel1);
        newScore = new JSlider();
        panel1.add(newScore, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Score");
        panel1.add(label1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        projectTitle = new JLabel();
        projectTitle.setEnabled(true);
        Font projectTitleFont = this.$$$getFont$$$("Unispace", Font.BOLD, 22, projectTitle.getFont());
        if (projectTitleFont != null) projectTitle.setFont(projectTitleFont);
        projectTitle.setText("Project");
        panel1.add(projectTitle, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$("Unispace", Font.BOLD, 22, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setText("Edit Project");
        main.add(label2, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        main.add(panel2, new GridConstraints(2, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        updateButton = new JButton();
        updateButton.setText("Update");
        panel2.add(updateButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        deleteProjectButton = new JButton();
        deleteProjectButton.setText("Delete Project");
        panel2.add(deleteProjectButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return main;
    }

}
