package me.craig.college.wsc.forms;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import me.craig.college.wsc.utils.Utils;

import javax.swing.*;
import java.awt.*;

/* Created by Craig on 06/04/2021 */
public class Help {
    private JTextArea securityText;
    private JPanel helpPane;
    private JTabbedPane tabbedPane1;

    public Help() {
        securityText.setLineWrap(true);
        tabbedPane1.addTab("Guide", null);
        securityText.setEditable(false);
        tabbedPane1.addChangeListener(changeEvent -> {
            String current = tabbedPane1.getTitleAt(tabbedPane1.getSelectedIndex());
            updateTextArea(current);
        });
    }

    private void updateTextArea(String current) {
        switch (current) {
            case "Security": {
                String security = "This program creates external files in order to retain information that it has created. In order to make this information private and secure, it is encrypted and any information generated can only be accessed on the computer that created it.";
                securityText.setText(security);
                break;
            }
            case "Guide": {
                String guide = "In order to use this program, you must first add a team. From there you will have access to adding Judges, more teams and projects. ";
                securityText.setText(guide);
                break;
            }
            default:
                securityText.setText("No Data");
                break;
        }
    }

    public static void showHelp() {
        Utils.setTheme();
        JFrame jFrame = new JFrame("Help");
        jFrame.setContentPane(new Help().helpPane);
        jFrame.setSize(300, 400);
        jFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        jFrame.setResizable(false);
        jFrame.setVisible(true);
        jFrame.setLocationRelativeTo(null);
        jFrame.setIconImage(WorldSkillsCompetition.instance.getIconLocation());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        helpPane = new JPanel();
        helpPane.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), 2, -1));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Unispace", Font.BOLD, 22, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("Help");
        helpPane.add(label1, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tabbedPane1 = new JTabbedPane();
        helpPane.add(tabbedPane1, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Security", panel1);
        securityText = new JTextArea();
        securityText.setText("This program creates external files in order to retain information that it has created. In order to make this information private and secure, it is encrypted and any information generated can only be accessed on the computer that created it.");
        panel1.add(securityText, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return helpPane;
    }

}
